//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEditOrder
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int OrderItemID { get; set; }
        public int ProductID { get; set; }
        public int ProductVariableID { get; set; }
        public string SKU { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public double TotalPrice { get; set; }
        public int Status { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
