
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IM_PJ.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PostWordpress
{

    public int ID { get; set; }

    public int PostPublicID { get; set; }

    public string WebWordpress { get; set; }

    public int PostWordpressID { get; set; }

    public Nullable<int> CategoryID { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Content { get; set; }

    public string Thumbnail { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

}

}
