//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockManager2
    {
        public int ID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ProductVariableID { get; set; }
        public string SKU { get; set; }
        public string ParentSKU { get; set; }
        public int Type { get; set; }
        public int Quantity { get; set; }
        public int QuantityCurrent { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
