//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config
    {
        public int ID { get; set; }
        public Nullable<double> NumOfDateToChangeProduct { get; set; }
        public Nullable<double> NumOfProductCanChange { get; set; }
        public Nullable<double> FeeChangeProduct { get; set; }
        public Nullable<double> FeeDiscountPerProduct { get; set; }
        public string ChangeGoodsRule { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SecurityCode { get; set; }
        public string RetailReturnRule { get; set; }
        public string CSSPrintBarcode { get; set; }
        public Nullable<int> HideProduct { get; set; }
    }
}
