//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebWordpress
    {
        public int ID { get; set; }
        public string Web { get; set; }
        public string WPKey { get; set; }
        public string WPSecret { get; set; }
        public string WPToken { get; set; }
        public string WPTokenSecret { get; set; }
        public string WCKey { get; set; }
        public string WCSecret { get; set; }
        public string WCPriceType { get; set; }
        public bool Active { get; set; }
    }
}
